name: Claude Code Review (JA)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    # 必要なら対象ファイルを絞る
    # paths:
    #   - "src/**/*.ts"
    #   - "src/**/*.tsx"
    #   - "src/**/*.js"
    #   - "src/**/*.jsx"

jobs:
  claude-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          prompt: |
            このプルリクエストを日本語でコードレビューしてください。以下の観点を重視してください：
            - コード品質とベストプラクティス
            - バグやセキュリティの懸念
            - パフォーマンスの問題
            - テストの不足

          claude_args: |
            --system-prompt "常に日本語で回答してください。簡潔で読みやすい形式で、見出しと箇条書きを使用してください。"
